"""Add region to swim standards

Revision ID: 1756d4952acb
Revises: 825d31cffd79
Create Date: 2026-07-12 16:48:21.300133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1756d4952acb'
down_revision = '825d31cffd79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('swim_standard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('region', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('swim_standard', schema=None) as batch_op:
        batch_op.drop_column('region')

    # ### end Alembic commands ###
