"""Change PB event to distance and stroke

Revision ID: 26245a0d8d00
Revises: 5eeeb5b77e31
Create Date: 2026-07-12 15:58:07.531098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26245a0d8d00'
down_revision = '5eeeb5b77e31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal_best', schema=None) as batch_op:
        batch_op.add_column(sa.Column('distance', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('stroke', sa.String(length=50), nullable=True))
        batch_op.drop_column('event')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal_best', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('stroke')
        batch_op.drop_column('distance')

    # ### end Alembic commands ###
