"""Add avatar and profile color

Revision ID: 493542ee28fc
Revises: e001f5860d79
Create Date: 2026-07-12 14:12:19.033234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '493542ee28fc'
down_revision = 'e001f5860d79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal_best', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('profile_color', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal_best', schema=None) as batch_op:
        batch_op.drop_column('profile_color')
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###
