"""Add pool to swim standards

Revision ID: 4f9b2c821bf2
Revises: 1756d4952acb
Create Date: 2026-07-12 16:52:08.908218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f9b2c821bf2'
down_revision = '1756d4952acb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('swim_standard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pool', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('swim_standard', schema=None) as batch_op:
        batch_op.drop_column('pool')

    # ### end Alembic commands ###
