"""add avatar settings

Revision ID: 5c0e254cda75
Revises: 493542ee28fc
Create Date: 2026-07-12 14:23:52.990885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c0e254cda75'
down_revision = '493542ee28fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal_best', schema=None) as batch_op:
        batch_op.drop_column('profile_color')
        batch_op.drop_column('avatar')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_emoji', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('avatar_color', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('avatar_color')
        batch_op.drop_column('avatar_emoji')

    with op.batch_alter_table('personal_best', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('profile_color', sa.VARCHAR(length=20), nullable=True))

    # ### end Alembic commands ###
